name: Deploy to Firebase Hosting on Merge
'on':
  push:
    branches: 
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAcocount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALPHABETA_ONE_PAGE_2023 }}'
          channelId: live
          projectId: alphabeta-one-page-2023
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels


